Feat/update
uswitch/segment-config-go pull request #3
Opened 2020-12-21 16:53 UTC by srikrishnavamsi

2020-12-22 11:20 UTC, srikrishnavamsi commented on segment/trackingPlans.go
> +	// fmt.Printf("%+v", tp)
uncomment or log debug / log trace

2021-03-13 14:43 UTC, Ninju requested changes

2021-03-13 14:43 UTC, Ninju commented on segment/types.go
> +	TrackingPlan TrackingPlan `json:"tracking_plan,omnitempty"`
typo - should be omitempty

2021-03-15 15:29 UTC, agouil commented on segment/types.go
> +	TrackingPlan TrackingPlan `json:"tracking_plan,omnitempty"`
👍

2021-03-15 15:33 UTC, Ninju approved these changes

2021-03-16 10:52 UTC, merged